FROM openjdk:11
COPY ./MovieService /code/MovieService
COPY ./Common /code/Common
COPY ./gradle /code/gradle
COPY ./gradlew /code/
COPY ./settings.gradle /code/
 
WORKDIR /code
RUN ./gradlew build
WORKDIR /app
RUN cp /code/MovieService/build/libs/*.jar /app/app.jar
 
EXPOSE 9000
CMD ["java", "-jar", "./app.jar"]