FROM openjdk:10
WORKDIR /usr/src/java-code
COPY . /usr/src/java-code/
RUN ./gradlew dependencies
RUN ./gradlew build
 
WORKDIR /usr/src/java-app
RUN cp /usr/src/java-code/AccountService/build/libs/*.jar .
RUN ls
RUN mv ./AccountService-1.0.0.jar ./app.jar
RUN ls
EXPOSE 8000
CMD ["java", "-jar", "app.jar"]