FROM openjdk:11
COPY ./AccountService /code/AccountService
COPY ./Common /code/Common
COPY ./gradle /code/gradle
COPY ./gradlew /code/
COPY ./settings.gradle /code/
 
WORKDIR /code
RUN ./gradlew build
WORKDIR /app
RUN cp /code/AccountService/build/libs/*.jar /app/app.jar
 
EXPOSE 8000
CMD ["java", "-jar", "./app.jar"]